name: Build application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - run: pnpm install --shamefully-hoist

      - run: pnpm generate
