name: Build application

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        
      - run: pnpm install --shamefully-hoist
        working-directory: frontend    
          
      - run: pnpm generate
        working-directory: frontend
